name: Checks on Pull-Request

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'

    - name: Run chmod to make gradlew executable
      run: chmod +x gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build --info
        
    - name: Publish Checkstyle Report
      uses: Juuxel/publish-checkstyle-report@v1
      if: always()
      with:
        reports: |
          ${{ env.ROOT_DIR }}/projects/*/build/reports/checkstyle/*.xml

    - name: Publish SpotBugs Report
      uses: jwgmeligmeyling/spotbugs-github-action@master
      if: always()
      with:
        path: '${{ env.ROOT_DIR }}/projects/*/build/reports/spotbugs/*.xml'
        
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: ${{ env.ROOT_DIR }}/projects/*/build/test-results/**/*.xml
